learn/Django/opsweb/dashboard/urls.py
#!/usr/bin/env python
#coding: utf-8
from django.conf.urls import include,url
from . import views
from . import user
from dashboard.user import group
from . import cmdb

urlpatterns=[
 url(r'^login/$',views.user_login),
 url(r'^logout/$',views.user_logout),
 url(r'^$',views.IndexView.as_view()),#as_view()去找类视图中的http－requets－method


 url(r'^user/', include([
    url(r'^userlist/$', user.UserLISTVIEW.as_view()),
    url(r'^modifystatus/$', user.ModifyUserStatusView.as_view()),
    url(r'^modifydepartment/$', user.ModifyDepartmentView.as_view()),
    url(r'^modifyphone/$', user.ModifyPhoneView.as_view()),
 ])),


 url(r'^permission/', include([
    url(r'^none/$', views.permission),
 ])),



 url(r'^group/', include([
    url(r'^$', group.GroupView.as_view()),
    url(r'^del/$', group.GroupdelView.as_view()),
    url(r'^list/$', group.GroupListView.as_view()),
    url(r'^usergroup/$', group.UserGroupView.as_view()),
    url(r'^delgroup/$', group.RemoveUserGroupView.as_view()),
    url(r'^permissionlist/$', group.GroupPermissionListView.as_view()),
    url(r'^permissions/$', group.GroupPermissionView.as_view()),
 ])),


 url(r'^cmdb/', include([
    url(r'^idclist/$', cmdb.ServerView),
 ])),
]

learn/Django/opsweb/opsweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^dashboard/',include("dashboard.urls")),
    url(r'^',include("dashboard.urls")),
]

learn/Django/opsweb/dashboard/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Server(models.Model):
    hostname = models.CharField(max_length=32,unique=True)
    ip       = models.CharField(max_length=15,unique=True)
    cpu      = models.CharField(max_length=50)
    mem      = models.CharField(max_length=50)
    disk     = models.CharField(max_length=50)
    sn       = models.CharField(max_length=50)
    idc      = models.CharField(max_length=50)
    ipinfo   = models.CharField("[{'eth0':1.1.1.1,'mac':''},{'eth0':2.2.2.2,'mac':''}]",max_length=255)
    product  = models.CharField(max_length=50)
    remark   = models.TextField(default='')

    def __str__(self):
        return "{} {}".format(self.hostname,self.ip)

    class Meta:
        db_table = 'server'
        permissions = (
            ('view_server', 'Can server info'),
        )

class Department(models.Model):
    name = models.CharField(max_length=32, null=True)

    class Meta:
        db_table = 'department'

#one-to-one
class Profile(models.Model):
    user            = models.OneToOneField(User)
    phone           = models.CharField(max_length=11, null=True)
    title           = models.CharField(max_length=32, null=True)
    # department      = models.CharField(max_length=32, null=True)
    department      = models.ForeignKey(Department, null=True)
    cn_name         = models.CharField('Chinese name', max_length=32, null=True)

    class Meta:
        db_table = 'user_profile'
        default_related_name = 'profile'

learn/Django/opsweb/dashboard/views.py
#coding: utf-8
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, QueryDict
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
import logging

logger = logging.getLogger('opsweb')



def user_login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html', {"title":"必优云运营平台"})
    elif request.method == 'POST':
        ret = {"status":0}
        ret["errmsg"] = '登陆成功'
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        #验证用户密码
        user = authenticate(username=username, password=password)
        print user
        # 如果用户名密码不存在/用户名不存在/密码不对 这些情况都会返回None
        if user is not None:
            if user.is_active:
                #  将用户信息写入session 将session_key写入cookie
                login(request, user)
                ret["next_url"] = '/'
            else:
                ret["status"] = 1
                ret["errmsg"] = '用户被禁用'
        else:
            ret["status"] = 2
            ret["errmsg"] = '用户名或密码错误'
        return JsonResponse(ret, safe=True)
    return JsonResponse(ret, safe=True)

@login_required
def user_logout(request):
    # 这一步会把session的值置为空，key不删除
    logout(request)
    return HttpResponseRedirect('/login')

class IndexView(View):
    @method_decorator(login_required)#哪个页面需要登录才能显示页面内容就加这个装饰器即可
    # @method_decorator(permission_required('dashboard.view_server', login_url=settings.PERMISSION_NONE_URL))
    def get(self, request):   #必须是method种的方法URL种的as_view()就是找类中的请求方法函数,比如get post put
        logger.error('首页error测试')
        logger.debug('首页debug测试')

        return render(request, "public/index.html")


def test_form(request):
    if request.method == 'GET':
        return render(request, 'test/test_form.html')
    elif request.method == 'POST':
        # print request.POST
        # print request.POST.lists()
        # print request.POST.dict()
        # username = request.POST.get('username', '')
        # print username
        # # fav = request.POST.get('fav')
        # #要写上第二个参数 默认值是什么 习惯问题
        # fav = request.POST.getlist('fav', [])
        # print fav
        #form表单提交的数据都写在body体里边（无论哪种方式提交）
        print request.body
        return HttpResponse('ok')
    #如果除了get&post之外的请求方式，取值方式如下：
    # else:
    #     data = QueryDict(request.body)
    #     fav = data.get('fav[]','')
    #     print fav
    #     fav2 = data.getlist('fav[]','')
    #     print fav2
    
@login_required
def permission(request):
    return render(request, 'public/permission.html')

learn/Django/opsweb/dashboard/templates/cmdb/idc.html
{% extends "public/layout.html" %}

{% block body %}
<div class="container" style="margin-top: 30px">
    <form id="addidc-form" >
      	机房名称 : <input type="text" name="name" class="form-group">
        <input type="submit" value="Add" class="btn btn-success">
     <!--   IP: <input type="text" name="ip" class="form-group">
       MEM: <input type="text" name="mem" class="form-group">
        IDC_ID<input type="text" name="idc_id" class="form-group">
        CREATE_TIME<input type="text" name="creat_time" class="form-group">
        <input type="submit" value="Add" class="btn btn-default"> -->
    </form>
    <br>
    <table border="1" class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Location</th>
               <!-- <th>idc_id</th>
                <th>creat_time</th> -->
            </tr>
        </thead>
        <tbody id="idc_table">
        </tbody>
    </table>
</div>

{% endblock%}


{% block js%}
<script>
        init_page()
        $('#addidc-form').on('submit',function () {
        var idcname = $('#addidc-form').find('[name="name"]')
        $.post('/addidc',{name:idcname.val()},function () {

            init_page()
            idcname.val('')
        })
        return false
    })

function init_page() {
    $.getJSON('/idclist',function (res) {
        var idc_str = ''
        $.each(res, function (i,v) {
            console.log(v)
            idc_str+='<tr>'
            idc_str+='<td>'+v[0]+'</td>'
            idc_str+='<td>'+v[1]+'</td>'
           // idc_str+='<td>'+v[2]+'</td>'
           //idc_str+='<td>'+v[3]+'</td>'
            idc_str+='</tr>'
        })
        $('#idc_table').html(idc_str)
    })

}

</script>

{% endblock %}

learn/Django/opsweb/dashboard/templates/user/group_permission.html
{% extends "public/layout.html" %}


{% block body %}
<!--<div class="col-sm-8">-->
    <table class="table table-striped">
        <!--如果后端使用listview的话就是遍历object_list-->
        <!--如果后端使用template模版的话就是遍历context_data['permissions']-->
        {% for permission in permissions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <!--<td>{{ permission.id }}</td>-->
                <td>{{ permission.name }}</td>
                <td>{{ permission.codename }}</td>
            </tr>
        {% endfor %}
    </table>
<!--</div>-->
{% endblock %}

learn/Django/opsweb/dashboard/templates/user/group_permission_list.html
{% extends "public/layout.html" %}

{% block css %}
    <style>
        .permission-content{width: 260px !important;}
        .permission-point{margin-left: 280px !important;}
    </style>
{% endblock %}

{% block body %}
    <dl class="dl-horizontal">
        <form action="" method="post" role="form" class="form-horizontal">
            <!--循环content_type-->
        {% for ct in content_type %}
            <dt class="permission-content">{{ ct.app_label }}---{{ ct.model }}: </dt>
            <dd class="permission-point">
                <ul class="list-unstyled">
                    {% for per in ct.permission_set.all %}
                        <li>
                            <input type="checkbox" name="permission" value="{{ per.id }}" {% if per.id in group_permissions %}checked{% endif %}>
                            <label>{{ per.name }}</label>
                        </li>
                    {% endfor %}
                </ul>
            </dd>
        {% endfor %}
            <div class="form-group form-footer">
                <div class="col-sm-offset-3 col-sm-8">
                    <input type="hidden" name="group" value="{{ group }}">
                    <input type="submit" class="btn btn-primary" value="修改">
                    <input type="submit" class="btn btn-warning" value="重置">
                </div>
            </div>
        </form>
    </dl>
{% endblock %}

learn/Django/opsweb/dashboard/templates/user/grouplist.html
{% extends "public/layout.html" %}

{% block body %}
    <table class="table table-striped">
        <caption>
            <button id="add_group" class="btn btn-primary" type="button">添加用户组</button>
        </caption>
        <tr>
            <th>用户组</th>
            <th>操作</th>
        </tr>
        {% for group in object_list %}
            <tr>
                <td>{{ group.name }}</td>
                <td>
                    <button class="btn btn-primary btn-sm show_group_users" data='{"gid":"{{ group.id }}","groupname":"{{ group.name }}"}'>成员列表</button>
                    <a class="btn btn-warning btn-sm show_group_users" href="/group/permissions/?gid={{ group.id }}">查看权限</a>
                    <a class="btn btn-danger btn-sm show_group_users" href="/group/permissionlist/?gid={{ group.id }}">修改权限</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <div class="modal fade" id="create_group" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4>添加group</h4>
                </div>
                <div class="modal-body form-inline">
                    <div class="form-group">
                        <label for="exampleInputName2">用户组：</label>
                        <input type="text" class="form-control" id="form_groupname" placeholder="请输入用户组名称" />
                    </div>
                    <button class="btn btn-primary" id="create_group_btn">提交</button>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>

            </div>
        </div>
    </div>


    <div class="modal fade" id="modal_show_group_user_list" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4>用户组名:<span id="modal_show_group_user_list_title"></span></h4>
                </div>
                <div class="modal-body form-inline" id="modal_show_group_user_content_list">

                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="确定">
                </div>

            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script>
        //<!--function是页面加载完毕之后的操作-->
        $(function(){
//            添加用户组
            $("#add_group").click(function(){
                var create_group_modal = $("#create_group");
                create_group_modal.modal("show");
                //执行添加用户组
                $("#create_group_btn").click(function(){
                    var group_input = $("#form_groupname");
                    var group_value = group_input.val();
                    create_group_modal.modal("hide");
                    if (group_value == ""){
                        swal("添加失败", "用户组名不能为空", 'error');
                        return false;
                    }
                    $.post("", {"name": group_value},function(res){
                        if(res.status==0){
                            swal({
                                "title": "添加成功",
                                "text": "",
                                "type": "success"
                            },function(){
                                setTimeout(function(){
                                    window.location.reload();
                                },50);
                            })
                        }else{
                            swal("操作失败", res.errmsg, "error");
                        }
                    })

                })

            });
        //查看组内成员
            $(".show_group_users").click(function(){
                var data = JSON.parse($(this).attr('data'));
                console.log(data);
                var groupid = data.gid;
                $.get("/group/usergroup/", {'gid':groupid},function(res){
                    console.log(res);
                    var html = '<table class="table table-striped">';
                    $.each(res, function(k, v){
                        html+= '<tr>';
                        html+= '<td>'+v.cn_name+'</td>';
                        html+= '<td>'+v.username+'</td>';
                        html+= '<td>'+v.email+'</td>';
                        html+= '<td><button class="btn btn-danger btn-sm del_group_user" data="'+v.id+'">删除</button></td>';
                        html+= '</tr>';
                    });
                    html+= '</table>';
                    console.log(html);
                    $('#modal_show_group_user_list_title').html(data.groupname);
                    $('#modal_show_group_user_content_list').html(html);
                    $('#modal_show_group_user_list').modal('show');
                    $('.del_group_user').click(function(){
                        var click_obj = $(this);
                        var userid = click_obj.attr('data');
                        console.log(userid);
                        console.log(data.gid);
                        $.ajax({
                            url:"/group/usergroup/",
                            type:"DELETE",
                            data:{"groupid":groupid, "userid":userid},
                        })
                    })
                })
               })
            })
    </script>
{% endblock %}

learn/Django/opsweb/dashboard/templates/user/login.html
<!DOCTYPE html>
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="index,follow">
    <meta name="Author" content="reboot">

    <link href="/static/img/favicon.ico" type="image/x-icon" rel="shortcut icon">
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/alert/sweet-alert.css" rel="stylesheet">
    <style type="text/css">
        body {
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #eee;
        }
        .form-signin {
          max-width: 330px;
          padding: 15px;
          margin: 0 auto;
        }
        </style>

    <title>Devops平台 - 管理员登陆</title>
    </head>
    <body>
        <!--loginbox again-->
    <div class="container">
            <form class="form-signin" id="loginform">
                <h2 class="form-signin-heading" style="text-align: center;">用户登录</h2>
                <div class="form-group">
                  <input type="text" id="username" class="form-control" name="username"  placeholder="请输入用户名"/>
                </div>
                <div class="form-group">
                    <input type="password" id="password" class="form-control" name="password" placeholder="请输入密码"/>
                </div>
                <button type="submit" class="btn btn-lg btn-primary btn-block">登录</button>
                <a id='forget'>忘记密码</a>
            </form>
      </div>



<script type="text/javascript" src="/static/vendor/alert/sweet-alert.min.js"></script>
<script type="text/javascript" src="/static/vendor/jquery/jquery.min.js"></script>

<script type="text/javascript">
/* 忘记密码提示*/
$("#forget").click(function() {
    str="请联系管理员帮您重置密码"+'\n'+"邮箱：sunfan666@gmail.com"
    swal(str)
});



/*用户登录*/
$('#loginform').on('submit',function(){
    var str = $('#loginform').serialize()
    console.log(str)
    //post提交的页面是当前页面，提交的数据是str，处理返回数据的函数
    //前端获取到用户输入的数据之后提交给后端验证，后端验证之后返回给前端状态0或非0
    $.post('#', str, function(res){
//        console.log(res)
        if (res.status == 0){
            swal({
                "title": res.errmsg,
                "text": "",
                "type": "success"
            },function(){
                $("#username").val("")
                $("#password").val("")
            });
//            alert("登陆成功")
            location.href=res.next_url
        }else{
            swal({
                title: res.errmsg,
                type: "error",
                confirmButtonText: "知道了"
            },function(){
                $("#username").val("")
                $("#password").val("")
            });
        }
    });
    return false;

})


</script>


</body></html>

learn/Django/opsweb/dashboard/templates/user/modify_department.html
<!--导入layout文件内容-->
{% extends 'public/layout.html' %}
<!--替换layout文件中留出的body块数据-->
{% block body %}
<form class="form-horizontal" method="post">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-5">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{ user_obj.email }}" disabled>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">部门</label>
    <div class="col-sm-5">
      <select class="form-control" name="department_id">
          <option value=0>请选择部门</option>
          {% for department in departments %}
          <option value="{{ department.id }}" {% if department.id == user_obj.profile.department.id %}selected{% endif %}>{{ department.name }}</option>
          {% endfor %}
</select>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="hidden" name="id" value="{{ user_obj.id }}">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>
{% endblock %}

learn/Django/opsweb/dashboard/templates/user/modify_userinfo.html
<!--导入layout文件内容-->
{% extends 'public/layout.html' %}
<!--替换layout文件中留出的body块数据-->
{% block body %}
<form class="form-horizontal" method="post">

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-5">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{ user_obj.email }}" disabled>
    </div>
  </div>

    <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">中文名</label>
    <div class="col-sm-5">
      <input type="text" class="form-control" id="inputEmail3" name="cn_name" value="{{ user_obj.profile.cn_name }}">
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">职位</label>
    <div class="col-sm-5">
      <input type="text" class="form-control" id="inputEmail3" name="title" value="{{ user_obj.profile.title }}">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">手机号</label>
    <div class="col-sm-5">
      <input type="text" class="form-control" name="phone" id="input-phone" placeholder="手机号" value="{{ user_obj.profile.phone }}">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="hidden" name="id" value="{{ user_obj.id }}">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>
{% endblock %}

learn/Django/opsweb/dashboard/templates/user/userlist.html
{% extends "public/layout.html" %}

{% block body %}
    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>用户id</th>
            <th>用户名</th>
            <th>中文名</th>
            <th>email</th>
            <th>phone</th>
            <th>所在组</th>
            <th>职位</th>
            <th>部门</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        {% for user in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.profile.name|default_if_none:'' }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.profile.phone }}</td>
            <td>
                {% for group in user.groups.all %}
                    {{ group.name }}&#12288;
                {% endfor %}
            </td>
            <td>{{ user.profile.title }}</td>
            <td>
                {{ user.profile.department.name|default_if_none:"无部门" }}
            </td>
            <td class="user_status">
                {% if user.is_active %}
                    <span class="glyphicon glyphicon-ok-circle text-success"></span>正常
                {% else %}
                    <span class="glyphicon glyphicon-warning-sign text-warning"></span>禁止
                {% endif %}
            </td>
            <td>
                <div class="btn-group">
                    <div class="btn-group">
                        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">
                            修改
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            {% if perms.dashboard.change_department %}
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/modifydepartment/?user={{ user.id }}">部门</a></li>
                            {% endif %}
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/modifyphone/?uid={{ user.id }}">手机号</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#" data='{"uid":"{{ user.id }}"}' class="user_to_group">添加指定组</a></li>
                        </ul>
                    </div>
                    {% if user.is_active %}
                        <button type="button" class="btn btn-sm btn-warning modify_user_status" status="true" data="{{ user.id }}">禁用</button>
                    {% else %}
                        <button type="button" class="btn btn-sm modify_user_status btn-info" status="false" data="{{ user.id }}">开启</button>
                    {% endif %}
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>

    <div class="panel-default">
        <center>
            <ul class="pagination">
                <li><a href="/user/userlist/?page=1">首页</a></li>
                    {% if page_obj.has_previous %}
                    <li><a href="/user/userlist/?page={{ page_obj.previous_page_number }}">上一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">上一页</a></li>
                    {% endif %}

                    {# {% for p in page_obj.paginator.page_range %} #}
                    {% for p in page_range %}
                        <li {% if page_obj.number == p %} class="active" {% endif %}><a href="/user/userlist/?page={{ p }}">{{ p }}</a></li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li><a href="/user/userlist/?page={{ page_obj.next_page_number }}">下一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">下一页</a></li>
                    {% endif %}
                <li><a href="/user/userlist/?page={{ page_obj.paginator.num_pages }}">末页</a></li>
            </ul>
        </center>
    </div>



    <div class="modal fade" id="user_to_group_modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 id="user_to_group_modal_title"></h4>
                </div>
                <div class="modal-body form-inline col-xs-6">
                    <select class="form-control" id="all_user_group">
                    </select>
                    <button class="btn btn-primary" id="user_to_group_btn">提交</button>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
    function change_user_status(status_td_obj, status){
        if (status == "true"){
            status_td_obj.html('<span class="glyphicon glyphicon-warning-sign text-warning"></span>禁止')
        }else{
            status_td_obj.html('<span class="glyphicon glyphicon-ok-circle text-success"></span>正常')
        }
    }
    function modify_user_status(user_id){
        $.post("/user/modifystatus/", {"user_id": user_id}, function(res){
            if (res.status != 0){
                swal({
                    title: res.errmsg,
                    type: "error",
                    confirmButtonText: "知道了"
                });
            }
        })
    }
    $(function(){
        $(".modify_user_status").click(function(){
            var click_obj = $(this);
            var status = click_obj.attr("status");
            if(status === "true"){
                click_obj.removeClass("btn-warning").addClass("btn-info").attr("status", "false").text("开启");
            }else{
                click_obj.removeClass("btn-info").addClass("btn-warning").attr("status", "true").text("禁用");
            }
            change_user_status(click_obj.parents("td").siblings(".user_status"), status);
            modify_user_status(click_obj.attr('data'));
        });

        /*
        *
        * 将用户添加到指定组
        *
        * */
        var uid;
        var user_to_group_modal = $("#user_to_group_modal");
        var all_user_group = $("#all_user_group");

        $(".user_to_group").click(function(){
            user_to_group_modal.modal("show");
            var data = JSON.parse($(this).attr('data'));
            uid = data.uid;
            $.get("/group/",{"uid":uid},function(res){
                html = '<option value="0">请选择用户组</option>';

                $.each(res, function(n, obj){
                    html += '<option value="'+obj.pk+'">'+obj.fields.name+'</option>';
                });
                all_user_group.html(html)
            });
            return false;
        });

        // 执行将用户添加到指定用户组
        $("#user_to_group_btn").click(function(){

            var url = "/group/usergroup/";
            var gid = all_user_group.val();
            user_to_group_modal.modal("hide");
            $.post(url, {"uid": uid, "gid": gid}, function(res){
                if(res.status == 0){
                    swal({
                        "title": "添加成功",
                        "text": "",
                        "type": "success"
                    },function(){
                        setTimeout(function(){
                            window.location.reload();
                        },50);
                    })
                }else{
                    swal("操作失败", res.errmsg, "error");
                }
            })
        })

    })
</script>
{% endblock %}